### ISSUE TITLE
show embeds content too

### ISSUE THREAD

**Issue by owocado** [Juby210/view-raw#2]
Hi,

thanks for this nice plugin. It works pretty well with normal text contents but when I try to view raw of text inside embeds, it just shows a blank line. Thought I would report on this.

Here's example embed:
![image](https://user-images.githubusercontent.com/24418520/93428946-f760d280-f8dd-11ea-8b73-5d967623842b.png)

and here's what is shows when i try to view raw of it:
![image](https://user-images.githubusercontent.com/24418520/93429008-12cbdd80-f8de-11ea-8d12-28571a9aef00.png)

**Comment by Juby210** [comment]
What about showing embeds json? I think that would be good way to show raw embeds.

**Comment by owocado** [comment]
That works too. 🙂

**Comment by Juby210** [comment]
Landed in 32c7ff6a7261a312eab6618b89e91e0f59e5f294!
